Feat/#74 member info
woohaengshi/backend pull request #84
Opened 2024-08-17 14:35 UTC by yaejinkong

# 📄 Work Description
- 회원 정보 조회 기능

# ⚙️ ISSUE
- closed #74 

# 📷 Screenshot
 - 포스트맨
<img width="539" alt="image" src="https://github.com/user-attachments/assets/3af9c99f-5bd6-4a9e-9fbe-fc737ef74468">

# 💬 To Reviewers
피그마 마이페이지에는 이메일이 없긴 하던데 우선 이름, 이메일, 비밀번호, 이미지, 코스를 조회하도록 하였습니다. 
개선할 점이나 추가해야 할 점이 있다면 리뷰 부탁드립니다!

2024-08-18 08:07 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    private String password;
회원 조회 시 비밀번호는 전달하면 안 될 것 같습니다 🥲

2024-08-18 08:07 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    public ShowMemberResponse(
private 으로 생성자를 구현해야 할 것 같습니다!

2024-08-18 08:07 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +}
제 response dto 참고하셔서 전체적으로 코드를 조금 수정하면 더 좋을 것 같아요 😊😊 public ~ of() 이런 식으로요!

2024-08-18 08:07 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +    @Override
제 생각에는 어노테이션으로 readonly = true 로 해주셔야 될 것 같습니다!

2024-08-18 08:07 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +
회원 검증하는 메소드가 다른 서비스에 보시면 구현되어 있는데 그 부분 참고하셔서 검증하는 부분을 분리하여 구현하시면 가독성이 더 좋을 것 같습니다 👍🏻

2024-08-18 18:43 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    private String password;
넵 수정하겠습니다!!

2024-08-18 18:44 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    public ShowMemberResponse(
앗 넵 알겠습니다!!

2024-08-18 18:47 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +}
아하 정적 팩토리 메서드를 사용해야 하는 이유를 잘 몰랐는데 이제 확실히 이해했습니다!  
of 메서드를 써서 수정해보겠습니다!! 감사합니다~😃

2024-08-18 18:51 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +    @Override
조회만 수행하는 메서드라서 readonly = true를 붙이는 거군요! 수정하겠습니다!!

2024-08-18 18:53 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +
처음에는 회원 검증 메서드를 분리해서 구현 했었는데 간결하게 써보고자 저렇게 변경하였습니다! 
가독성을 위해 다시 분리하겠습니다!!

2024-08-18 22:08 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +
아 회원 정보 조회라서 따로 boolean 값으로 안 받고 바로 memebr를 받은 다음 처리한거면 db 를 덜 조회하는 쪽이 아무래도 (제 생각에는) 더 좋을 것 같네요!! 👍🏻
예외 처리 해주는 부분은 분리하는게 좀 더 깔끔해 보일수도 있지만 굳이 하진 않으셔도 될 것 같아요 🌝 이 부분은 예진님이 보시기에 더 좋다고 생각하시는 코드로 하시면 될 것 같습니다 ~!

2024-08-18 22:13 UTC, qbobl5 commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +@Transactional(readOnly = true)
이 부분 class 위에는 @Transactional 만 붙이고,
아래에서 필요한 부분만 따로 readOnly = true 붙여주는 것으로 통일했던 것 같아요! 😉😉 이 부분만 수정하면 될 것 같아요~!~!

2024-08-19 00:11 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +
아하 그렇군용!! 그럼 이대로 두겠습니다!! 감사합니다 🤍

2024-08-19 00:12 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +@Transactional(readOnly = true)
앗 넵! 수정하겠습니다~!!!!!! 🥰

2024-08-19 01:21 UTC, rlfrkdms1 requested changes

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    public static ShowMemberResponse of(
```java
public static ShowMemberResponse from(Member member) {
    return ~
}
```
와 같은 방식으로 작성하면 더 가독성 좋을 것 같아요 ~!

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/main/java/com/woohaengshi/backend/controller/MemberController.java
> +@RequestMapping("/api/v1/members/info")
uri를 `/api/v1/members`로 해도 괜찮을 것 같아요 ~

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/main/java/com/woohaengshi/backend/controller/MemberController.java
> +    public ShowMemberResponse getMemberInfo(@MemberId Long memberId) {
저희 그때 컨트롤러 단에서는 show, 서비스단에선 get, repository 단에선 find를 사용하기로 했던 것 같아요 ~ 그래서 메서드명도 이에 맞춰서 작성해주시면 더 좋을 것 같습니다 ㅎㅎ

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +                        .orElseThrow(() -> new WoohaengshiException(ErrorCode.MEMBER_NOT_FOUND));
이 코드는 추후에 같은 service 클래스 내의 다른 로직에서도 많이 사용될 수 있을 것 같아서 `findMemberById(memberId)`의 형태로 메서드를 분리하면 더 좋을 것 같습니다 !

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
> +public class MemberControllerTest {
컨트롤러 테스트는 제가 만들어놓은 클래스가 있는데, 그걸 상속받아서 사용하시면 더 좋을 것 같아요 !

2024-08-19 01:21 UTC, rlfrkdms1 commented on src/test/java/com/woohaengshi/backend/service/MemberServiceTest.java
> +        assertEquals(ErrorCode.MEMBER_NOT_FOUND, exception.getErrorCode());
위에서 `assertThat`을 사용하셔서 여기도 `assertThat`을 사용하시는게 어떨까요?

2024-08-19 07:52 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
> +    public static ShowMemberResponse of(
오오 훨씬 더 깔끔해지네요!! from 메서드를 쓰는 걸로 수정했습니다!!

2024-08-19 07:53 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/controller/MemberController.java
> +@RequestMapping("/api/v1/members/info")
넵 수정하겠습니다!!

2024-08-19 07:53 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/controller/MemberController.java
> +    public ShowMemberResponse getMemberInfo(@MemberId Long memberId) {
아하 제가 그 부분을 놓쳤네욥 ㅠ ㅠ !! showMemberInfo로 변경하겠습니다~!!

2024-08-19 09:56 UTC, yaejinkong commented on src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
> +                        .orElseThrow(() -> new WoohaengshiException(ErrorCode.MEMBER_NOT_FOUND));
넵 분리하겠습니다!!

2024-08-19 09:57 UTC, yaejinkong commented on src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
> +public class MemberControllerTest {
아하 유용한 클래스가 있었네요!! 상속받아서 테스트 하도록 변경하겠습니다!!

2024-08-19 09:58 UTC, yaejinkong commented on src/test/java/com/woohaengshi/backend/service/MemberServiceTest.java
> +        assertEquals(ErrorCode.MEMBER_NOT_FOUND, exception.getErrorCode());
넵 ! 그럼 assertThatThrownBy를 사용하는 걸로 변경하겠습니다!

2024-08-19 23:16 UTC, qbobl5 approved these changes

2024-08-20 00:49 UTC, rlfrkdms1 approved these changes

2024-08-20 00:51 UTC, merged